name: Close Old PRs
on:
  # Schedule updates (At minute 0 past every 24th hour)
  schedule: [{ cron: "0 0 * * *" }]

jobs:
  close-old-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Close Old PRs
        run: |
          open_prs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" \
            | jq -r '.[] | .number')

          for pr in $open_prs; do
            # Get the last updated timestamp of the pull request
            last_updated=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$pr" \
              | jq -r '.updated_at')

            days_since_update=$(( ( $(date +%s) - $(date -d "$last_updated" +%s) ) / 86400 ))

            if [ $days_since_update -gt 30 ]; then
              curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"state":"closed"}' \
                "https://api.github.com/repos/${{ github.repository }}/pulls/$pr"
            fi
          done
